from wtforms.validators import *

MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 25

USERNAME_REGEXP = r'^[a-z_][a-z0-9_]*$'
USERNAME_REGEXP_MESSAGE = 'Username must start with a letter or underscore and contain only letters, numbers, or underscores'

USERNAME_VALIDATORS = [
    Length(min=MIN_USERNAME_LENGTH, max=MAX_USERNAME_LENGTH),
    Regexp(USERNAME_REGEXP, message=USERNAME_REGEXP_MESSAGE),
]

MIN_NAME_LENGTH = 1
MAX_NAME_LENGTH = 35

NAME_VALIDATORS = [Length(min=MIN_NAME_LENGTH, max=MAX_NAME_LENGTH)]

PASSWORD_HASH_LENGTH = 128

MIN_CHAT_NAME_LENGTH = 1
MAX_CHAT_NAME_LENGTH = 50

CHAT_NAME_VALIDATORS = [
    Length(min=MIN_CHAT_NAME_LENGTH, max=MAX_CHAT_NAME_LENGTH),
]

MIN_MESSAGE_TEXT_LENGTH = 1
MAX_MESSAGE_TEXT_LENGTH = 500

CHAT_NOT_FOUND_MESSAGE = {'error': 'Chat not found'}
INVALID_DATA_MESSAGE = {'error': 'Invalid data'}
